name: 'The PR&Marketing Agency'
favicon: null
layout_spectrum: 0.29751515784300864
typography_spectrum: 0.37617698847316206
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9273935325909406
  lightness: 0.18217402137815952
  saturation: 0.8577319879550487
  rhythmicContrast: 0.2971851537004113
purpose: []
