name: The PR&Marketing Agency
favicon: null
layout_spectrum: 0
typography_spectrum: 0.69958
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0f1519'
    - '#c1c4bd'
    - '#667e8c'
    - '#535353'
  brandStrength: 1
  lightness: 0.18217402137815952
  saturation: 0.8577319879550487
  rhythmicContrast: 0.2971851537004113
purpose: []
